version: '3'

services:
  database:
    image: mysql:5.7
    container_name: frete-rapido-database
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: freterapido
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
